# Generated by Django 4.1.3 on 2022-12-03 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainourservicetext',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='mainourservicetext',
            name='text',
            field=models.TextField(),
        ),
    ]
