# Generated by Django 4.1.3 on 2022-12-05 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_mainourservicetext_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='order',
            field=models.IntegerField(default=99),
        ),
    ]
