# Generated by Django 4.1.3 on 2022-12-05 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_service_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintechnologycard',
            name='order',
            field=models.IntegerField(default=99),
        ),
        migrations.AddField(
            model_name='portifolio',
            name='order',
            field=models.IntegerField(default=99),
        ),
    ]
