# Generated by Django 4.1.3 on 2022-12-05 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_partnerfeedback_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='industrytitle',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
