# Generated by Django 4.1.3 on 2022-12-05 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_vacancy_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle1', models.CharField(max_length=255)),
                ('text1', models.TextField(blank=True, null=True)),
                ('subtitle2', models.CharField(max_length=255)),
                ('text2', models.TextField(blank=True, null=True)),
                ('hide_second_part', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('Project', 'Project'), ('Resume', 'Resume')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
