# Generated by Django 4.1.3 on 2022-12-05 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_formcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientmessage',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.service'),
            preserve_default=False,
        ),
    ]
