# Generated by Django 4.1.3 on 2022-12-06 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_clientmessage_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientmessage',
            old_name='last_name',
            new_name='company',
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.TextField(),
        ),
    ]
