# Generated by Django 4.1.3 on 2022-12-06 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_rename_last_name_clientmessage_company_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactinfo',
            old_name='address',
            new_name='address_uz',
        ),
        migrations.RenameField(
            model_name='formcontent',
            old_name='subtitle1',
            new_name='subtitle1_uz',
        ),
        migrations.RenameField(
            model_name='formcontent',
            old_name='subtitle2',
            new_name='subtitle2_uz',
        ),
        migrations.RenameField(
            model_name='formcontent',
            old_name='text1',
            new_name='text1_en',
        ),
        migrations.RenameField(
            model_name='formcontent',
            old_name='text2',
            new_name='text1_ru',
        ),
        migrations.RenameField(
            model_name='formcontent',
            old_name='title',
            new_name='title_uz',
        ),
        migrations.RenameField(
            model_name='industry',
            old_name='title',
            new_name='title_uz',
        ),
        migrations.RenameField(
            model_name='industrytitle',
            old_name='text',
            new_name='text_uz',
        ),
        migrations.RenameField(
            model_name='industrytitle',
            old_name='title',
            new_name='title_uz',
        ),
        migrations.RenameField(
            model_name='mainaboutusstatistic',
            old_name='subtitle',
            new_name='subtitle_uz',
        ),
        migrations.RenameField(
            model_name='mainaboutusstatistic',
            old_name='title',
            new_name='title_uz',
        ),
        migrations.RenameField(
            model_name='mainaboutustitle',
            old_name='text',
            new_name='text_uz',
        ),
        migrations.RenameField(
            model_name='mainaboutustitle',
            old_name='title',
            new_name='title_uz',
        ),
        migrations.RenameField(
            model_name='mainourservicetext',
            old_name='text',
            new_name='text_uz',
        ),
        migrations.RenameField(
            model_name='mainourservicetext',
            old_name='title',
            new_name='title_uz',
        ),
        migrations.RenameField(
            model_name='maintechnologycard',
            old_name='title',
            new_name='title_uz',
        ),
        migrations.RenameField(
            model_name='partner',
            old_name='name',
            new_name='name_uz',
        ),
        migrations.RenameField(
            model_name='partnerfeedback',
            old_name='feedback',
            new_name='feedback_uz',
        ),
        migrations.RenameField(
            model_name='partnerfeedback',
            old_name='partner_bio',
            new_name='partner_bio_uz',
        ),
        migrations.RenameField(
            model_name='partnerfeedback',
            old_name='partner_name',
            new_name='partner_name_uz',
        ),
        migrations.RenameField(
            model_name='partnerfeedbacktitle',
            old_name='text',
            new_name='text_uz',
        ),
        migrations.RenameField(
            model_name='partnerfeedbacktitle',
            old_name='title',
            new_name='title_uz',
        ),
        migrations.RenameField(
            model_name='portifolio',
            old_name='description',
            new_name='description_en',
        ),
        migrations.RenameField(
            model_name='portifolio',
            old_name='title',
            new_name='title_uz',
        ),
        migrations.RenameField(
            model_name='portifoliocategory',
            old_name='title',
            new_name='title_uz',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='text',
            new_name='text_uz',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='title',
            new_name='title_uz',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='name',
            new_name='name_uz',
        ),
        migrations.RenameField(
            model_name='vacancy',
            old_name='short_title',
            new_name='short_title_uz',
        ),
        migrations.RenameField(
            model_name='vacancy',
            old_name='text',
            new_name='text_uz',
        ),
        migrations.RenameField(
            model_name='vacancy',
            old_name='title',
            new_name='title_uz',
        ),
        migrations.RemoveField(
            model_name='industry',
            name='text',
        ),
        migrations.RemoveField(
            model_name='maintitle',
            name='title',
        ),
        migrations.RemoveField(
            model_name='team',
            name='title',
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='address_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='address_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='formcontent',
            name='subtitle1_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='formcontent',
            name='subtitle1_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='formcontent',
            name='subtitle2_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='formcontent',
            name='subtitle2_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='formcontent',
            name='text1_uz',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formcontent',
            name='text2_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formcontent',
            name='text2_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formcontent',
            name='text2_uz',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formcontent',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='formcontent',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='industry',
            name='text_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='industry',
            name='text_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='industry',
            name='text_uz',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='industry',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='industry',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='industrytitle',
            name='text_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='industrytitle',
            name='text_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='industrytitle',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='industrytitle',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mainaboutusstatistic',
            name='subtitle_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mainaboutusstatistic',
            name='subtitle_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mainaboutusstatistic',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mainaboutusstatistic',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mainaboutustitle',
            name='text_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mainaboutustitle',
            name='text_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mainaboutustitle',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mainaboutustitle',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mainourservicetext',
            name='text_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mainourservicetext',
            name='text_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mainourservicetext',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mainourservicetext',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='maintechnologycard',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='maintechnologycard',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='maintitle',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='maintitle',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='maintitle',
            name='title_uz',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partner',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='name_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='partnerfeedback',
            name='feedback_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partnerfeedback',
            name='feedback_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partnerfeedback',
            name='partner_bio_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='partnerfeedback',
            name='partner_bio_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='partnerfeedback',
            name='partner_name_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='partnerfeedback',
            name='partner_name_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='partnerfeedbacktitle',
            name='text_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partnerfeedbacktitle',
            name='text_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partnerfeedbacktitle',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='partnerfeedbacktitle',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='portifolio',
            name='description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portifolio',
            name='description_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portifolio',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='portifolio',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='portifoliocategory',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='portifoliocategory',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='text_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='text_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='name_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='title_uz',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacancy',
            name='short_title_en',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='short_title_ru',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='text_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='text_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
