# Generated by Django 4.1.3 on 2022-12-14 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_teamcategory_team_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamcategory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='teamcategory',
            name='order',
            field=models.IntegerField(default=99),
        ),
    ]
